apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker-app
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: expense-tracker-container
          image: anshuhtwt/expense-tracker
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 256Mi
